export const questions = [
  {
    id: 1,
    question: "In a 1980s April Fools' prank, the BBC announced that Big Ben was switching to what?",
    options: ["A digital clock", "A countdown timer", "A musical chime system", "An atomic clock"],
    correct: 0,
    fact: "The BBC World Service had listeners absolutely convinced before revealing it was a gag.",
  },
  {
    id: 2,
    question: "In 1957, what vegetable did the BBC famously claim was being harvested from trees in their 'spaghetti harvest' hoax?",
    options: ["Pasta", "Spaghetti", "Tomatoes", "Noodles"],
    correct: 1,
    fact: "Hundreds of viewers called in asking where they could buy their own spaghetti trees.",
  },
  {
    id: 3,
    question: "In 1996, Taco Bell announced it had purchased a famous American landmark. Which one?",
    options: ["The Statue of Liberty", "The Washington Monument", "The Liberty Bell", "Mount Rushmore"],
    correct: 2,
    fact: "They planned to rename it the 'Taco Liberty Bell.' The public outrage was very real.",
  },
  {
    id: 4,
    question: "As an April Fools' prank, Burger King created a toothpaste flavored like their signature burger. What was the flavor called?",
    options: ["Flame-Grilled Fresh", "Whopper", "Meaty Mint", "BK Classic"],
    correct: 1,
    fact: "The 'Whopper toothpaste' campaign went viral. People genuinely wanted to try it.",
  },
  {
    id: 5,
    question: "What animal did the BBC trick viewers into believing could fly in a 2008 April Fools' prank?",
    options: ["Seals", "Penguins", "Tortoises", "Polar bears"],
    correct: 1,
    fact: "The segment showed 'flying penguins' migrating to the Amazon. It looked remarkably real.",
  },
  {
    id: 6,
    question: "What country calls April Fools' Day 'Poisson d'Avril,' and what does that mean?",
    options: ["Italy — April Butterfly", "France — April Fish", "Spain — Spring Fool", "Belgium — Paper Trick"],
    correct: 1,
    fact: "Children in France tape paper fish to people's backs as the classic prank.",
  },
  {
    id: 7,
    question: "Amazon released an April Fools' product called 'Petlexa' — a pet-friendly version of which device?",
    options: ["Amazon Fire TV", "Amazon Echo", "Amazon Kindle", "Amazon Ring"],
    correct: 1,
    fact: "Petlexa promised to understand barks and meows. Pets, reportedly, were unimpressed.",
  },
  {
    id: 8,
    question: "In 2008, which app pranked users by claiming to help dogs learn how to code?",
    options: ["Duolingo", "WonderPaw", "Codecademy", "Pawgramming"],
    correct: 1,
    fact: "The app claimed dogs could learn JavaScript within weeks. Good boy, undefined.",
  },
  {
    id: 9,
    question: "⏳ FINAL QUESTION NEXT — are you ready to see your scores?",
    isTransition: true,
    options: ["Yes, I'm ready →"],
    correct: 0,
    fact: "",
  },
  {
    id: 10,
    isProposal: true,
    question: "Will you be my girlfriend?",
    fact: "Life is full of pranks and small deceptions — but my love for you is the only thing that's undeniably real.",
  },
];
